name: Build Squidify Wrapper

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Windows'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'macOS'
            platform: 'darwin/universal'
            os: 'macos-latest'
          - name: 'Linux'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'

    runs-on: ${{ matrix.build.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install dependencies (Ubuntu)
      if: matrix.build.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Install dependencies (macOS)
      if: matrix.build.os == 'macos-latest'
      run: |
        # No additional dependencies needed for macOS

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Get Go dependencies
      run: go mod download

    - name: Build Wails app
      run: wails build -platform ${{ matrix.build.platform }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: squidify-${{ matrix.build.name }}
        path: |
          build/bin/
        retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: squidify-*
        merge-multiple: true
        
    - name: List downloaded files
      run: ls -la
      
    - name: Create release archives
      run: |
        # Create archives for each platform
        mkdir -p release-files
        
        # Find and archive Windows build
        if [ -d "squidify-Windows" ]; then
          cd squidify-Windows && zip -r ../release-files/squidify-windows.zip . && cd ..
        fi
        
        # Find and archive macOS build  
        if [ -d "squidify-macOS" ]; then
          cd squidify-macOS && tar -czf ../release-files/squidify-macos.tar.gz . && cd ..
        fi
        
        # Find and archive Linux build
        if [ -d "squidify-Linux" ]; then
          cd squidify-Linux && tar -czf ../release-files/squidify-linux.tar.gz . && cd ..
        fi
        
        ls -la release-files/
        
    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: release-files/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Build and test on every commit
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Get Go dependencies
      run: go mod download

    - name: Test Go code
      run: go test ./...

    - name: Verify Wails project
      run: wails doctor
